updated for checking and caching packages in nextjs.yml

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -13,21 +13,36 @@ on:
   workflow_dispatch:
 
 jobs:
-  # Build job
   build:
     runs-on: self-hosted
     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Setup Node
+      - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
           node-version: "20"
-          cache: ${{ steps.detect-package-manager.outputs.manager }}
 
-      - name: Install Yarn (if required)
-        run: npm install -g yarn
+      - name: Check if Yarn is installed
+        run: |
+          if ! command -v yarn &> /dev/null
+          then
+            echo "Yarn not found, installing..."
+            npm install -g yarn
+          else
+            echo "Yarn is already installed."
+          fi
+
+      - name: Check if PM2 is installed
+        run: |
+          if ! command -v pm2 &> /dev/null
+          then
+            echo "PM2 not found, installing..."
+            npm install -g pm2
+          else
+            echo "PM2 is already installed."
+          fi
 
       - name: Install dependencies
         run: yarn install
@@ -39,6 +54,6 @@ jobs:
         run: |
           touch .env
           echo "${{ secrets.leezo_env_secrets }}" >> .env
-          
+
       - name: Start pm2 process
         run: pm2 startOrRestart ecosystem.config.js
